name: generate-libs-docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          node-version: "10.x"

      - name: Git Clone
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Generate libs doc
        run: |
          pwd
          npm run gen:doc
      - name: Git Init
        run: |
          pwd
          cd ./docs
          git init
      - name: Git Commit
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_USER_EMAIL: ${{ secrets.GITHUB_USER_EMAIL }}
        run: |
          ls
          cd ./docs
          git add .
          git config user.email "${GITHUB_USER_EMAIL}"
          git config user.name "${GITHUB_USER}"
          git commit -m "update github pages"
      - name: Git Push
        env:
          ACCESS_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
        run: |
          cd ./docs
          git push --set-upstream --force --quiet "https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master:gh-pages

  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Git Clone
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          pwd
          cd ./libs/topology
          npm install

      - name: build
        run: |
          pwd
          cd ./libs/topology
          npm run build

      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
        run: |
          pwd
          cd ./dist/topology-core
          npm publish

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Git Clone
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          pwd
          cd ./bundle
          npm install

      - name: build
        run: |
          pwd
          cd ./bundle
          npm run build

      - name: push release
        uses: meeDamian/github-release@v1.0.1
        with:
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
          tag: v0.0.14
          name: bundle.js
          body: >
            This is a bundle js.
          files: >
            bundle/demo/topology.bundle.js
